kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
- name: General Test
  image: golang
  commands:
  - go test ./... -covermode=count -coverprofile=coverage.out
  when:
  event:
    exclude:
    - pull_request

  when:
  event:
    exclude:
    - pull_request